# Open Gitlab Issue to make this possible: https://gitlab.com/gitlab-org/gitlab/-/issues/28987
include: '//reference/gitlab-ci/maven/base.yml'

.jar-snapshot-template:
  extends: .mvn
  only:
    - master
  except: # Do not run when preparing a release
    variables:
      - $CI_COMMIT_MESSAGE =~ /.*prepare release.*/ || ($CI_BUILD_REF_NAME == "master" && $CI_COMMIT_MESSAGE =~ /.*maven-release-plugin.*/)

.jar-release-template:
  extends: .mvn
  only:
    - /^v(\d+\.)+(\*|\d+)$/
  except:
    - branches
