apiVersion: v1
kind: Pod
metadata:
  name: gcloud
spec:
  containers:
    - name: gcloud
      image: google/cloud-sdk:alpine
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
