apiVersion: v1
kind: Pod
metadata:
  name: kafka
  namespace: foundation
spec:
  containers:
  - name: kafka
    image: bitnami/kafka
    command:
      - sleep
      - "36000000"
    imagePullPolicy: IfNotPresent
