apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-test
  labels:
    app: nginx-test
data:
  nginx.conf: |
    events {
    }
    http {
      map $host $feature_deployment {
        # https://serverfault.com/questions/1056539/how-to-get-substring-of-a-string-with-nginx
        default                    http://default-http-backend.kube-system.svc.cluster.local:80;
        "~^console-(?<branch>feature-\\d{4})\\.dev\\.strmprivacy\\.io$"  http://console-$branch.core.svc.cluster.local:8888/metrics;
      }
      
      server {
        listen 80;
        location / {
          resolver kube-dns.kube-system.svc.cluster.local ipv6=off;
          proxy_pass $feature_deployment;
        }
      }
    }
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    app: nginx-test
spec:
  volumes:
    - name: nginx-test
      configMap:
        name: nginx-test
  containers:
    - name: nginx
      image: nginx:alpine3.17
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      volumeMounts:
        - name: nginx-test
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
  restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-test
  name: nginx-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: nginx-test
  type: ClusterIP
