apiVersion: v1
kind: Pod
metadata:
  name: openssl
spec:
  containers:
  - name: openssl
    image: frapsoft/openssl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
